version: "3.8"

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      target: build
      args:
        MIX_ENV: dev
    container_name: app
    command: iex -S mix phx.server
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - .:/app
      - app_build:/app/_build/
      - app_deps:/app/deps
    depends_on:
      - db
    networks:
      - solfacil

  db:
    image: postgres:13.5
    container_name: app_db
    environment:
      POSTGRES_PASSWORD: solfacil
      POSTGRES_USER: solfacil
      POSTGRES_DB: app_dev
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - solfacil
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

networks:
  solfacil:
    name: solfacil

volumes:
  app_build:
  app_deps:
  postgres_data:



